name: Build buildenv

on:
  push:
    branches:
      - master
    paths: 
      - 'script/docker/**'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          persist-credentials: false

      - name: Build Docker
        run: |
          make docker-buildenv
          docker login --username=filvenus --password ${{ secrets.DOCKER_PASSWORD }}
          make push-buildenv
